### ISSUE TITLE
Strange delay when switching languages 🤔 

### ISSUE THREAD

**Issue by kutyel** [lucamug/elm-ecommerce#1]
Hey!

Thanks so much for this app! It is amazing and puts so many things together it is a great demo!! 🙌🏻 

I noticed a strange delay when switching languages, some texts change immediately and some others take 0.5s or so.

I'm also willing to contribute so if I'm given some pointer as to where this might be happening in the codebase maybe I can give it a go! 😉

**Comment by lucamug** [comment]
Hi @kutyel , thank you for the feedback. This behavior is expected. The app is simulating a delay when getting the product data. In the demo, this data is coming actually from a hard-coded JSON string. This JSON string also contains the translation of the products. But the translations of the app itself are in the code because the quantity is small. This is why you see this difference.

I should add a note somewhere.

**Comment by kutyel** [comment]
Nice, thanks for the explanation! 😉
